apiVersion: v1
kind: Service
metadata:
  name: mypriv-service
spec:
  selector:
    app: mypriv
  ports:
    - name: http-frontend
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: http-db
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: http-backend
      protocol: TCP
      port: 4700
      targetPort: 4700
  type: NodePort